
services:
  customer-portal-ui:
    container_name: customer-portal-ui
    build:
      context: ./apps/customer-portal-ui
      dockerfile: dockerfile

    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    env_file:
      - .env
    volumes:
      - ./apps/customer-portal-ui/src:/app/src
      - ./apps/customer-portal-ui/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network


networks:
  my_network:
    driver: bridge