# syntax=docker.io/docker/dockerfile:1

FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY app ./app
COPY public ./public
COPY styles ./styles
COPY components ./components
COPY lib ./lib

COPY next.config.ts .
COPY tsconfig.json .
COPY tailwind.config.ts .
COPY postcss.config.mjs .
COPY middleware.ts .



CMD npm run dev